PKGDIR          ?= .
L4DIR           ?= $(PKGDIR)/../..

TARGET               = simple-server simple-client
REQUIRES_LIBS       := libstdc++
SRC_CC_simple-server = server.cc
SRC_CC_simple-client = client.cc

include $(L4DIR)/mk/prog.mk

